"""RESEARCH Domain Models — Web Research, News, Content, Knowledge Base."""

import enum
from datetime import datetime
from decimal import Decimal
from typing import Optional, List

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Enum as SQLEnum,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.sqlite import JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from axiom.data.database import DeclarativeBase


class ResearchBase(DeclarativeBase):
    """Base for RESEARCH domain models."""
    metadata = MetaData(schema="research")


class ResearchStatus(str, enum.Enum):
    """Research report status."""

    PLANNED = "planned"
    IN_PROGRESS = "in_progress"
    REVIEW = "review"
    COMPLETED = "completed"
    PUBLISHED = "published"
    ARCHIVED = "archived"


class ContentType(str, enum.Enum):
    """Content piece types."""

    BLOG_POST = "blog_post"
    ARTICLE = "article"
    WHITEPAPER = "whitepaper"
    CASE_STUDY = "case_study"
    NEWSLETTER = "newsletter"
    SOCIAL_POST = "social_post"
    VIDEO_SCRIPT = "video_script"
    EMAIL_SEQUENCE = "email_sequence"
    LANDING_PAGE = "landing_page"
    REPORT = "report"


class ContentStatus(str, enum.Enum):
    """Content status."""

    IDEA = "idea"
    OUTLINE = "outline"
    DRAFTING = "drafting"
    REVIEW = "review"
    APPROVED = "approved"
    PUBLISHED = "published"
    ARCHIVED = "archived"


class NewsSource(str, enum.Enum):
    """News source categories."""

    RSS = "rss"
    API = "api"
    SCRAPED = "scraped"
    MANUAL = "manual"
    WEBHOOK = "webhook"


class Sentiment(str, enum.Enum):
    """Sentiment analysis."""

    POSITIVE = "positive"
    NEGATIVE = "negative"
    NEUTRAL = "neutral"


# ──────────────────────────────────────────────────────────────────────────────
# RESEARCH REPORTS
# ──────────────────────────────────────────────────────────────────────────────

class ResearchReport(ResearchBase):
    """Research report generated by Nova/Atlas."""

    __tablename__ = "research_reports"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    uuid: Mapped[str] = mapped_column(String(36), unique=True, nullable=False, index=True)

    # Identity
    title: Mapped[str] = mapped_column(String(500), nullable=False, index=True)
    slug: Mapped[str] = mapped_column(String(500), unique=True, nullable=False, index=True)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Content
    executive_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    content: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Markdown
    content_html: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    methodology: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    findings: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    recommendations: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)

    # Metadata
    status: Mapped[ResearchStatus] = mapped_column(
        SQLEnum(ResearchStatus), default=ResearchStatus.PLANNED, nullable=False, index=True
    )
    topic: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, index=True)
    industry: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, index=True)
    keywords: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    tags: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)

    # Attribution
    author_agent: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)  # nova, atlas
    reviewer_agent: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    approved_by: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # Sources
    sources: Mapped[List[dict]] = mapped_column(JSON, default=list, nullable=False)  # [{title, url, type, credibility}]
    source_urls: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)

    # Metrics
    word_count: Mapped[int] = mapped_column(Integer, default=0)
    reading_time_minutes: Mapped[int] = mapped_column(Integer, default=0)
    credibility_score: Mapped[Optional[Decimal]] = mapped_column(Numeric(3, 2), nullable=True)  # 0-1

    # Dates
    research_started_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    research_completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    published_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True, index=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    content_pieces: Mapped[List["ContentPiece"]] = relationship(
        "ContentPiece", back_populates="research_report", lazy="selectin"
    )

    __table_args__ = (
        Index("ix_research_reports_status_topic", "status", "topic"),
        Index("ix_research_reports_author_status", "author_agent", "status"),
    )

    def __repr__(self) -> str:
        return f"<ResearchReport(id={self.id}, title={self.title[:50]}, status={self.status.value})>"


# ──────────────────────────────────────────────────────────────────────────────
# NEWS ARTICLES
# ──────────────────────────────────────────────────────────────────────────────

class NewsArticle(ResearchBase):
    """News article from feeds, APIs, or scraping."""

    __tablename__ = "news_articles"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    uuid: Mapped[str] = mapped_column(String(36), unique=True, nullable=False, index=True)

    # Identity
    title: Mapped[str] = mapped_column(String(500), nullable=False, index=True)
    url: Mapped[str] = mapped_column(String(1000), unique=True, nullable=False, index=True)
    canonical_url: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)

    # Content
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    content: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Full text
    content_html: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Author & publication
    author: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    publication: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, index=True)
    publication_domain: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, index=True)

    # Classification
    categories: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    tags: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    keywords: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    entities: Mapped[List[dict]] = mapped_column(JSON, default=list, nullable=False)  # Named entities

    # Sentiment
    sentiment: Mapped[Optional[Sentiment]] = mapped_column(SQLEnum(Sentiment), nullable=True, index=True)
    sentiment_score: Mapped[Optional[Decimal]] = mapped_column(Numeric(3, 2), nullable=True)  # -1 to 1

    # Source
    source_type: Mapped[NewsSource] = mapped_column(SQLEnum(NewsSource), nullable=False)
    source_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)  # Feed ID, etc.

    # Media
    image_url: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)
    video_url: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)

    # Dates
    published_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True, index=True)
    fetched_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False, index=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=func.now(), onupdate=func.now(), nullable=False
    )

    # Metadata
    language: Mapped[str] = mapped_column(String(10), default="en", nullable=False)
    word_count: Mapped[int] = mapped_column(Integer, default=0)
    credibility_score: Mapped[Optional[Decimal]] = mapped_column(Numeric(3, 2), nullable=True)
    is_processed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True)

    __table_args__ = (
        Index("ix_news_articles_published_source", "published_at", "source_type"),
        Index("ix_news_articles_sentiment_published", "sentiment", "published_at"),
        Index("ix_news_articles_domain_published", "publication_domain", "published_at"),
    )

    def __repr__(self) -> str:
        return f"<NewsArticle(id={self.id}, title={self.title[:50]}, source={self.source_type.value})>"


# ──────────────────────────────────────────────────────────────────────────────
# WEB PAGES
# ──────────────────────────────────────────────────────────────────────────────

class WebPage(ResearchBase):
    """Crawled/scraped web page."""

    __tablename__ = "web_pages"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    uuid: Mapped[str] = mapped_column(String(36), unique=True, nullable=False, index=True)

    # Identity
    url: Mapped[str] = mapped_column(String(1000), unique=True, nullable=False, index=True)
    canonical_url: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)
    title: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    domain: Mapped[str] = mapped_column(String(255), nullable=False, index=True)

    # Content
    content: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    content_html: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    markdown: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Metadata
    meta_description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    meta_keywords: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    og_tags: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)
    structured_data: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)  # JSON-LD

    # Classification
    page_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)  # article, product, landing, etc.
    categories: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    tags: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)

    # Content analysis
    word_count: Mapped[int] = mapped_column(Integer, default=0)
    readability_score: Mapped[Optional[Decimal]] = mapped_column(Numeric(5, 2), nullable=True)
    sentiment: Mapped[Optional[Sentiment]] = mapped_column(SQLEnum(Sentiment), nullable=True)
    sentiment_score: Mapped[Optional[Decimal]] = mapped_column(Numeric(3, 2), nullable=True)
    entities: Mapped[List[dict]] = mapped_column(JSON, default=list, nullable=False)

    # Links
    internal_links: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    external_links: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)

    # Crawler metadata
    status_code: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    content_type: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    content_length: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    response_headers: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)

    # Processing
    is_indexed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_processed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    processing_error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Dates
    last_crawled_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False, index=True)
    last_modified_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=func.now(), onupdate=func.now(), nullable=False
    )

    __table_args__ = (
        Index("ix_web_pages_domain_crawled", "domain", "last_crawled_at"),
        Index("ix_web_pages_type_indexed", "page_type", "is_indexed"),
    )

    def __repr__(self) -> str:
        return f"<WebPage(url={self.url[:80]}, domain={self.domain})>"


# ──────────────────────────────────────────────────────────────────────────────
# CONTENT PIECES
# ──────────────────────────────────────────────────────────────────────────────

class ContentPiece(ResearchBase):
    """Content piece for marketing/sales."""

    __tablename__ = "content_pieces"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    uuid: Mapped[str] = mapped_column(String(36), unique=True, nullable=False, index=True)

    # Identity
    title: Mapped[str] = mapped_column(String(500), nullable=False, index=True)
    slug: Mapped[str] = mapped_column(String(500), unique=True, nullable=False, index=True)
    content_type: Mapped[ContentType] = mapped_column(SQLEnum(ContentType), nullable=False, index=True)

    # Content
    outline: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    content: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Markdown
    content_html: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # SEO
    meta_title: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    meta_description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    focus_keyword: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    keywords: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)

    # Status
    status: Mapped[ContentStatus] = mapped_column(
        SQLEnum(ContentStatus), default=ContentStatus.IDEA, nullable=False, index=True
    )

    # Attribution
    research_report_id: Mapped[Optional[int]] = mapped_column(
        BigInteger, ForeignKey("research_reports.id"), nullable=True
    )
    author_agent: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)  # creator
    reviewer_agent: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    approved_by: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # Distribution
    distribution_channels: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    published_urls: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)

    # Metrics
    views: Mapped[int] = mapped_column(Integer, default=0)
    clicks: Mapped[int] = mapped_column(Integer, default=0)
    conversions: Mapped[int] = mapped_column(Integer, default=0)
    engagement_score: Mapped[Optional[Decimal]] = mapped_column(Numeric(5, 2), nullable=True)

    # Dates
    draft_completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    reviewed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    approved_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    published_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True, index=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    research_report: Mapped[Optional["ResearchReport"]] = relationship("ResearchReport", back_populates="content_pieces")

    __table_args__ = (
        Index("ix_content_pieces_type_status", "content_type", "status"),
        Index("ix_content_pieces_published", "published_at"),
    )

    def __repr__(self) -> str:
        return f"<ContentPiece(id={self.id}, title={self.title[:50]}, type={self.content_type.value})>"


# ──────────────────────────────────────────────────────────────────────────────
# KNOWLEDGE BASE
# ──────────────────────────────────────────────────────────────────────────────

class KnowledgeEntry(ResearchBase):
    """Knowledge base entry - curated, searchable knowledge."""

    __tablename__ = "knowledge_entries"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    uuid: Mapped[str] = mapped_column(String(36), unique=True, nullable=False, index=True)

    # Identity
    title: Mapped[str] = mapped_column(String(500), nullable=False, index=True)
    slug: Mapped[str] = mapped_column(String(500), unique=True, nullable=False, index=True)

    # Content
    content: Mapped[str] = mapped_column(Text, nullable=False)  # Markdown
    content_html: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Classification
    category: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, index=True)
    subcategory: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    tags: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    keywords: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)

    # Versioning
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    previous_version_id: Mapped[Optional[int]] = mapped_column(
        BigInteger, ForeignKey("knowledge_entries.id"), nullable=True
    )

    # Quality
    is_verified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    verified_by: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    verified_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    credibility_score: Mapped[Optional[Decimal]] = mapped_column(Numeric(3, 2), nullable=True)

    # Usage
    view_count: Mapped[int] = mapped_column(Integer, default=0)
    helpful_count: Mapped[int] = mapped_column(Integer, default=0)
    not_helpful_count: Mapped[int] = mapped_column(Integer, default=0)

    # Ownership
    owner_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, index=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=func.now(), onupdate=func.now(), nullable=False
    )
    published_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True, index=True)

    # Self-referential relationship
    previous_version: Mapped[Optional["KnowledgeEntry"]] = relationship(
        "KnowledgeEntry", remote_side=[id], backref="next_version"
    )

    __table_args__ = (
        Index("ix_knowledge_entries_category_verified", "category", "is_verified"),
        Index("ix_knowledge_entries_owner", "owner_id"),
    )

    def __repr__(self) -> str:
        return f"<KnowledgeEntry(id={self.id}, title={self.title[:50]}, category={self.category})>"